"""
Tests for ResourceAgent LLM enrichment (Phase 8.2-A).

Covers:
- LLM enriches resources with personalized_description/learning_tips
- reasoning is generated by LLM when available
- Rule fallback when LLM fails or is unavailable
- RESOURCE_CATALOG structure preserved
"""

import pytest
from src.agents.resource_agent import (
    ResourceAgent,
    ResourceItem,
    ResourceRecommendation,
)


# ── Mock LLM Provider ────────────────────────────────────────


class MockLLMProvider:
    """Simulates an LLM that returns enrichment JSON."""

    def __init__(self, response_json: dict = None, should_fail: bool = False):
        self._response = response_json
        self._should_fail = should_fail
        self.model = "mock-model"

    @property
    def is_available(self):
        return True

    def generate(self, prompt: str, system_prompt: str = "", **kwargs):
        if self._should_fail:
            raise RuntimeError("LLM unavailable")
        import json as _json

        class FakeResponse:
            content = _json.dumps(self._response or {})
            success = True
            error = ""

        return FakeResponse()


# ── Helpers ──────────────────────────────────────────────────


def _make_profile(kb="junior_dev", cog="visual_dominant", pace="normal"):
    return {"knowledge_base": kb, "cognitive_style": cog, "learning_pace": pace}


def _make_resources():
    return [
        ResourceItem(
            type="documentation",
            title="Python Networking Guide",
            reason="Learn socket programming",
            difficulty="beginner",
            estimated_minutes=30,
        ),
        ResourceItem(
            type="video",
            title="TCP/IP Basics",
            reason="Visual networking concepts",
            difficulty="beginner",
            estimated_minutes=25,
        ),
    ]


# ── Tests ────────────────────────────────────────────────────


class TestResourceAgentLLMEnrichment:
    """LLM enhances resources without changing catalog structure."""

    def test_llm_adds_personalized_description(self):
        """Resources get personalized_description from LLM."""
        agent = ResourceAgent()
        llm = MockLLMProvider(
            response_json={
                "resources": [
                    {
                        "index": 1,
                        "personalized_description": "Great for your visual learning style",
                        "learning_tips": "Watch the video first",
                    },
                    {
                        "index": 2,
                        "personalized_description": "Perfect for hands-on practice",
                        "learning_tips": "Code along with examples",
                    },
                ],
                "reasoning": "Tailored for visual learner with socket focus",
            }
        )
        agent.set_llm_provider(llm)

        resources = _make_resources()
        enriched, reasoning = agent._enrich_with_llm(
            resources, _make_profile(), "Learn networking", ["socket", "tcp"]
        )

        assert len(enriched) == 2
        assert enriched[0].personalized_description == "Great for your visual learning style"
        assert enriched[0].learning_tips == "Watch the video first"
        assert enriched[1].personalized_description == "Perfect for hands-on practice"
        assert enriched[1].learning_tips == "Code along with examples"
        assert reasoning == "Tailored for visual learner with socket focus"

    def test_llm_preserves_catalog_structure(self):
        """LLM enrichment never changes resource type/title/difficulty."""
        agent = ResourceAgent()
        llm = MockLLMProvider(
            response_json={
                "resources": [
                    {"index": 1, "personalized_description": "desc", "learning_tips": "tip"},
                ],
                "reasoning": "strategy",
            }
        )
        agent.set_llm_provider(llm)

        original = _make_resources()
        enriched, _ = agent._enrich_with_llm(
            original, _make_profile(), "goal", []
        )

        for i in range(len(original)):
            assert enriched[i].type == original[i].type
            assert enriched[i].title == original[i].title
            assert enriched[i].difficulty == original[i].difficulty
            assert enriched[i].estimated_minutes == original[i].estimated_minutes

    def test_rule_fallback_when_llm_fails(self):
        """LLM failure returns original resources + empty reasoning."""
        agent = ResourceAgent()
        llm = MockLLMProvider(should_fail=True)
        agent.set_llm_provider(llm)

        resources = _make_resources()
        enriched, reasoning = agent._enrich_with_llm(
            resources, _make_profile(), "goal", []
        )

        assert enriched is resources  # same object returned
        assert reasoning == ""

    def test_rule_fallback_when_no_provider(self):
        """Without LLM provider, resources returned unchanged."""
        agent = ResourceAgent()
        # Never called set_llm_provider

        resources = _make_resources()
        enriched, reasoning = agent._enrich_with_llm(
            resources, _make_profile(), "goal", []
        )

        assert enriched is resources
        assert reasoning == ""

    def test_recommend_uses_llm_when_provider_set(self):
        """recommend() calls _enrich_with_llm when provider is available."""
        agent = ResourceAgent()
        llm = MockLLMProvider(
            response_json={
                "resources": [
                    {"index": 1, "personalized_description": "desc", "learning_tips": "tip"},
                ],
                "reasoning": "LLM strategy",
            }
        )
        agent.set_llm_provider(llm)

        result = agent.recommend(
            profile=_make_profile(),
            goal="Learn Python networking",
            knowledge_gaps=["socket"],
        )

        assert isinstance(result, ResourceRecommendation)
        # With LLM: reasoning comes from LLM
        assert result.reasoning == "LLM strategy"

    def test_recommend_falls_back_without_provider(self):
        """Without provider, recommend() uses rule reasoning."""
        agent = ResourceAgent()

        result = agent.recommend(
            profile=_make_profile(),
            goal="Learn networking",
            knowledge_gaps=["socket"],
        )

        assert isinstance(result, ResourceRecommendation)
        # Without LLM: reasoning comes from rule
        assert "学习目标" in result.reasoning
        assert "策略" in result.reasoning

    def test_empty_resources_bypasses_llm(self):
        """Empty resource list returns immediately without LLM call."""
        agent = ResourceAgent()
        llm = MockLLMProvider(should_fail=True)  # would fail if called
        agent.set_llm_provider(llm)

        enriched, reasoning = agent._enrich_with_llm(
            [], _make_profile(), "goal", []
        )

        assert enriched == []
        assert reasoning == ""

    def test_to_dict_includes_llm_fields(self):
        """to_dict() includes personalized_description and learning_tips."""
        item = ResourceItem(
            type="documentation",
            title="Test",
            reason="test",
            personalized_description="Personalized for you",
            learning_tips="Study tip",
        )

        d = item.to_dict()
        assert d["personalized_description"] == "Personalized for you"
        assert d["learning_tips"] == "Study tip"

    def test_to_dict_omits_empty_llm_fields(self):
        """to_dict() omits personalized_description/learning_tips when empty."""
        item = ResourceItem(type="doc", title="T", reason="r")

        d = item.to_dict()
        assert "personalized_description" not in d
        assert "learning_tips" not in d
