"""
Phase 9.5 — Image Provider

Generates concept illustrations. API → SVG placeholder → mock.
"""
import base64
from .base import BaseProvider, ProviderResult


PLACEHOLDER_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 300">
  <rect width="400" height="300" fill="#f0f4ff" rx="8"/>
  <text x="200" y="140" text-anchor="middle" font-family="Arial" font-size="18" fill="#4a5568">
    {title}
  </text>
  <text x="200" y="170" text-anchor="middle" font-family="Arial" font-size="13" fill="#718096">
    AI-generated illustration placeholder
  </text>
  <circle cx="200" cy="80" r="30" fill="#667eea" opacity="0.3"/>
  <rect x="120" y="200" width="160" height="40" fill="#667eea" opacity="0.15" rx="4"/>
</svg>"""


class ImageProvider(BaseProvider):
    name = "image"
    cost_per_token = 0.005  # USD per image

    def _api_available(self) -> bool:
        import os
        return bool(os.environ.get("FAL_KEY") or os.environ.get("OPENAI_API_KEY"))

    def _generate_via_api(self, topic, title, concepts, profile, goal, level):
        # In production: call FAL.ai / DALL-E
        # For now: generate an enhanced SVG with concept info
        concept = concepts[0] if concepts else topic
        svg = self._build_concept_svg(topic, concept, level)
        img_b64 = base64.b64encode(svg.encode()).decode()

        return ProviderResult(
            content=f"data:image/svg+xml;base64,{img_b64}",
            content_format="base64",
            media_urls=[f"data:image/svg+xml;base64,{img_b64}"],
            provider_name="fal",
            fallback_level=0,
            cost_usd=self.cost_per_token,
        )

    def _generate_via_rules(self, topic, title, concepts, profile, goal, level):
        concept = concepts[0] if concepts else topic
        title = title or topic
        svg = self._build_concept_svg(topic, concept, level)
        img_b64 = base64.b64encode(svg.encode()).decode()

        return ProviderResult(
            content=f"data:image/svg+xml;base64,{img_b64}",
            content_format="base64",
            media_urls=[f"data:image/svg+xml;base64,{img_b64}"],
            provider_name="svg_placeholder",
            fallback_level=1,
        )

    def _build_concept_svg(self, topic: str, concept: str, level: str) -> str:
        colors = {"beginner": "#48bb78", "intermediate": "#4299e1", "advanced": "#9f7aea"}
        color = colors.get(level, "#4299e1")

        return f"""<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 350">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#f7fafc;stop-opacity:1"/>
      <stop offset="100%" style="stop-color:#edf2f7;stop-opacity:1"/>
    </linearGradient>
  </defs>
  <rect width="500" height="350" fill="url(#bg)" rx="12"/>
  <rect x="40" y="40" width="420" height="60" fill="{color}" opacity="0.15" rx="8"/>
  <text x="250" y="78" text-anchor="middle" font-family="Arial, sans-serif"
        font-size="20" font-weight="bold" fill="#2d3748">{topic}</text>
  <circle cx="250" cy="180" r="50" fill="{color}" opacity="0.2"/>
  <text x="250" y="178" text-anchor="middle" font-family="Arial, sans-serif"
        font-size="16" fill="{color}">📚</text>
  <text x="250" y="205" text-anchor="middle" font-family="Arial, sans-serif"
        font-size="14" font-weight="bold" fill="#4a5568">{concept[:30]}</text>
  <rect x="60" y="250" width="380" height="60" fill="white" rx="6" stroke="#e2e8f0"/>
  <text x="250" y="278" text-anchor="middle" font-family="Arial, sans-serif"
        font-size="13" fill="#718096">Illustration of {concept[:30]}</text>
  <text x="250" y="298" text-anchor="middle" font-family="Arial, sans-serif"
        font-size="11" fill="#a0aec0">Level: {level} · Generated by A3 ImageProvider</text>
</svg>"""

    def _generate_mock(self, topic: str, title: str) -> ProviderResult:
        svg = PLACEHOLDER_SVG.replace("{title}", topic[:40])
        img_b64 = base64.b64encode(svg.encode()).decode()
        return ProviderResult(
            content=f"data:image/svg+xml;base64,{img_b64}",
            content_format="base64",
            provider_name="mock",
            fallback_level=2,
        )
