"""
Phase 9.5 — PPT Provider

Generates .pptx slides using python-pptx (optional dependency).
Falls back to Markdown slides if python-pptx not available.
"""
import os
import tempfile
from .base import BaseProvider, ProviderResult


class PPTProvider(BaseProvider):
    name = "ppt"
    cost_per_token = 0.01

    def _api_available(self) -> bool:
        return False  # PPT is always local generation

    def _generate_via_api(self, topic, title, concepts, profile, goal, level):
        return self._generate_via_rules(topic, title, concepts, profile, goal, level)

    def _generate_via_rules(self, topic, title, concepts, profile, goal, level):
        title = title or topic
        slides_md = self._build_slides_markdown(topic, title, concepts, level)
        file_path = ""

        # Try python-pptx
        try:
            from pptx import Presentation
            from pptx.util import Inches, Pt

            prs = Presentation()
            prs.slide_width = Inches(13.333)
            prs.slide_height = Inches(7.5)

            # Title slide
            slide = prs.slides.add_slide(prs.slide_layouts[0])
            slide.shapes.title.text = title
            if slide.placeholders[1]:
                slide.placeholders[1].text = f"Topic: {topic} | Level: {level}"

            # Content slides
            for i, concept in enumerate(concepts[:8], 1):
                slide = prs.slides.add_slide(prs.slide_layouts[1])
                slide.shapes.title.text = concept
                body = slide.placeholders[1]
                tf = body.text_frame
                tf.text = f"Key concept {i}: Understanding {concept}"
                p = tf.add_paragraph()
                p.text = f"• This concept is fundamental to {topic}"
                p.level = 1
                p = tf.add_paragraph()
                p.text = f"• Practical applications include various use cases in the field"
                p.level = 1

            # Summary slide
            slide = prs.slides.add_slide(prs.slide_layouts[1])
            slide.shapes.title.text = "Summary"
            body = slide.placeholders[1]
            tf = body.text_frame
            tf.text = f"Key takeaways from {title}:"
            for c in concepts:
                p = tf.add_paragraph()
                p.text = f"• {c}"
                p.level = 1

            fd, file_path = tempfile.mkstemp(suffix=".pptx", prefix="a3_slides_")
            os.close(fd)
            prs.save(file_path)

        except ImportError:
            pass  # python-pptx not installed — return Markdown only

        return ProviderResult(
            content=slides_md,
            content_format="markdown",
            file_path=file_path,
            provider_name="rule",
            fallback_level=1 if file_path else 2,
        )

    def _build_slides_markdown(self, topic: str, title: str, concepts: list, level: str) -> str:
        lines = [
            f"# {title}",
            "",
            f"**Topic:** {topic} | **Level:** {level} | **Slides:** {len(concepts) + 2}",
            "",
            "---",
            "",
            "## Slide 1: Title",
            f"# {title}",
            f"### {topic}",
            f"**Level:** {level}",
            "",
            "---",
            "",
        ]
        for i, concept in enumerate(concepts[:8], 1):
            lines.append(f"## Slide {i+1}: {concept}")
            lines.append("")
            lines.append(f"- Understanding **{concept}** is essential for mastering {topic}")
            lines.append(f"- This concept provides a foundation for more advanced topics")
            lines.append(f"- Real-world applications demonstrate the importance of {concept}")
            lines.append(f"- Practice exercises help reinforce your understanding")
            lines.append("")
            lines.append("---")
            lines.append("")

        lines.append(f"## Slide {len(concepts) + 2}: Summary")
        lines.append("")
        lines.append("### Key Takeaways")
        for c in concepts:
            lines.append(f"- ✅ **{c}**")
        lines.append("")
        lines.append(f"*Generated by A3 PPTProvider*")

        return "\n".join(lines)

    def _generate_mock(self, topic: str, title: str) -> ProviderResult:
        return ProviderResult(
            content=f"# {title or topic}\n\n## Slide 1\n\nMock presentation for {topic}.",
            content_format="markdown",
            provider_name="mock",
            fallback_level=2,
        )
