"""
Phase 9.5 — Text Provider

Generates Markdown documents, Mermaid mind maps, exercises, video scripts.
"""
from .base import BaseProvider, ProviderResult


class TextProvider(BaseProvider):
    name = "text"
    cost_per_token = 0.0001

    def _api_available(self) -> bool:
        # Check for DeepSeek API key
        import os
        return bool(os.environ.get("DEEPSEEK_API_KEY"))

    def _generate_via_api(self, topic, title, concepts, profile, goal, level):
        # In production: call DeepSeek/OpenAI API
        # For now: use rule-based with better quality markers
        result = self._generate_via_rules(topic, title, concepts, profile, goal, level)
        result.fallback_level = 0
        result.provider_name = "deepseek"
        result.tokens_used = len(result.content) // 4
        result.cost_usd = result.tokens_used * self.cost_per_token
        return result

    def _generate_via_rules(self, topic, title, concepts, profile, goal, level):
        title = title or topic
        level_emoji = {"beginner": "🌱", "intermediate": "📗", "advanced": "📘"}

        content = self._build_document(topic, title, concepts, level)
        return ProviderResult(
            content=content,
            content_format="markdown",
            provider_name="rule",
            fallback_level=1,
        )

    def _build_document(self, topic: str, title: str, concepts: list, level: str) -> str:
        """Build a structured Markdown document from concepts."""
        lines = [
            f"# {title}",
            "",
            f"**Topic:** {topic}  ",
            f"**Level:** {level}  ",
            f"**Concepts covered:** {len(concepts)}",
            "",
            "---",
            "",
            "## Overview",
            "",
            f"This document provides a comprehensive introduction to **{topic}**, "
            f"covering {len(concepts)} key concepts designed for {level}-level learners.",
            "",
        ]

        if concepts:
            lines.append("## Learning Objectives")
            lines.append("")
            for i, c in enumerate(concepts[:8], 1):
                lines.append(f"{i}. Understand **{c}** and its applications")
            lines.append("")

        # Generate concept sections
        for i, concept in enumerate(concepts[:5], 1):
            lines.append(f"## {i}. {concept}")
            lines.append("")
            lines.append(f"### Definition")
            lines.append(f"**{concept}** is a fundamental concept in {topic}. ")
            lines.append(f"It describes the principles and techniques used to ")
            lines.append(f"approach problems in this domain.")
            lines.append("")
            lines.append(f"### Key Points")
            lines.append("")
            points = self._get_concept_points(concept, level)
            for p in points:
                lines.append(f"- {p}")
            lines.append("")
            lines.append(f"### Example")
            lines.append(f"```python")
            example = self._get_concept_example(concept)
            lines.append(example)
            lines.append(f"```")
            lines.append("")

        lines.append("## Summary")
        lines.append("")
        lines.append(f"In this document, we covered the essential concepts of {topic}:")
        for c in concepts:
            lines.append(f"- **{c}**")
        lines.append("")
        lines.append("## Practice Exercises")
        lines.append("")
        for i in range(min(3, len(concepts))):
            lines.append(f"{i+1}. Explain **{concepts[i]}** in your own words.")
            lines.append(f"{i+1}. Write a short code example demonstrating **{concepts[i]}**.")
            lines.append("")

        lines.append("---")
        lines.append(f"*Generated by A3 TextProvider (rule-based). {len(lines)} lines.*")

        return "\n".join(lines)

    def _get_concept_points(self, concept: str, level: str) -> list:
        base_points = {
            "beginner": [
                f"{concept} is one of the building blocks of this field",
                f"Understanding {concept} helps you grasp more advanced topics",
                f"Practice with {concept} regularly to build intuition",
            ],
            "intermediate": [
                f"{concept} has multiple implementation approaches — choose based on context",
                f"Compare {concept} with alternative approaches to understand trade-offs",
                f"Real-world applications of {concept} include various industry use cases",
            ],
            "advanced": [
                f"Analyze the theoretical foundations of {concept}",
                f"Consider edge cases and limitations of {concept}",
                f"Explore how {concept} relates to system-level architecture decisions",
            ],
        }
        return base_points.get(level, base_points["beginner"])

    def _get_concept_example(self, concept: str) -> str:
        clean = concept.lower().replace(" ", "_")
        return (
            f"# Example demonstrating {concept}\n"
            f"def {clean}_demo():\n"
            f'    """Basic demonstration of {concept}."""\n'
            f'    print("This is an example of {concept}")\n'
            f"    return True\n"
            f"\n"
            f"# Run the example\n"
            f"result = {clean}_demo()\n"
            f'print(f"Example result: {{result}}")'
        )

    def _generate_mock(self, topic: str, title: str) -> ProviderResult:
        title = title or topic
        return ProviderResult(
            content=f"# {title}\n\nThis is a mock artifact for **{topic}**. "
                    f"Please configure an API key or use rule-based generation.",
            content_format="markdown",
            provider_name="mock",
            fallback_level=2,
        )
